### ISSUE TITLE
Include Newline at end of NEWS entry

### ISSUE THREAD

**Issue by sweeneyde** [python/blurb_it#256]
The NEWS entry added by blurb-it does not contain a newline at the end of the file, which makes the Docs CI check fail since the addition of sphinx-lint in https://github.com/python/cpython/pull/31097

See https://github.com/python/cpython/pull/31266 :
```
Error: [1] ../Misc/NEWS.d/next/Documentation/2022-02-10-23-40-54.bpo-44953.ZvrfXw.rst:0: No newline at end of file (no-newline-at-end-of-file).
```

**Comment by Mariatta** [comment]
I think this should take care of it: https://github.com/python/blurb_it/pull/257

**Comment by sweeneyde** [comment]
Thanks for the very fast turn-around time!

**Comment by Mariatta** [comment]
Thanks you for the report and the review! The change has been deployed. Please try.

**Comment by sweeneyde** [comment]
It worked! The Docs CI passed the "Check documentation" step, and the Azure Pipelinze CI passed its "Build Docs" step.

**Comment by vstinner** [comment]
That was quick, thanks @Mariatta! Thanks to your nice service, a contributor was able to easily add a NEWS entry to his PR: https://github.com/python/cpython/pull/29693 ;-)
