### ISSUE TITLE
Update Blurb-It to GitHub Issues

### ISSUE THREAD

**Issue by sweeneyde** [python/blurb_it#269]
I still see a field labeled `bpo-`on the "Blurb It!" form entry page. Presumably, this should be changed to `gh-issue-` and the output should be changed similarly.

It looks like [blurb has been updated](https://github.com/python/core-workflow/pull/431), but just not blurb_it yet.

**Comment by Mariatta** [comment]
Thanks for the report. We just needed to merge PR #265.
It should be deployed in a few minutes. Please reload the page.

**Comment by sweeneyde** [comment]
I don't know if it's an issue with my browser or something, but when I navigate to https://blurb-it.herokuapp.com/ and then click "Sign in with GitHub", nothing happens: instead of redirecting to the form page with the text boxes, it just refreshes the same https://blurb-it.herokuapp.com/ page.

**Comment by Mariatta** [comment]
I will look into this.

**Comment by Mariatta** [comment]
I missed setting an environment variable on Heroku. It should be working now.
Please refresh the page first and try signing in again. You may be asked to re-authorize the app.

**Comment by sweeneyde** [comment]
Thank you!

This looks mostly good: https://github.com/python/cpython/pull/91436, except cpython-cla-bot doesn't think that blurb-it has signed its CLA.

**Comment by Mariatta** [comment]
Great!
We need the bots (blurb-it and miss-islington) to be added to the cla-bot's allow list, but I don't have the permission for that. I have asked @ezio-melotti and @ambv to look into it.
