### ISSUE TITLE
Allow adding "skip news"

### ISSUE THREAD

**Issue by jdemeyer** [python/blurb_it#37]
It would be nice if blurb_it could also add the `skip news` label for PRs where a `NEWS` item is not needed. For me, the missing `skip news` label is the most common reason why my CPython pull requests get the red cross.

**Comment by methane** [comment]
I think comitter should decide news is required or not.
I don't ignore PRs only because red cross.

**Comment by jdemeyer** [comment]
> I think comitter should decide news is required or not.

The committer should **decide** but PR author should be able to **propose**. Just like the committer decides what gets merged but the PR author proposes the patch.

> I don't ignore PRs only because red cross.

Maybe you don't, but at least @willingc said "I rarely look at a PR that does not have a green checkmark" (https://discuss.python.org/t/github-labels-and-pr-review-workflow/237)

**Comment by Mariatta** [comment]
I personally think it is ok for non-committer to apply the skip `news label` to pass the CI.
If a core dev disagrees, it is quite easy to remove the label.

blurb-it (GitHub App) might not have the permission to add label. We might need to do this using bedevere's OAuth token.

**Comment by Mariatta** [comment]
Many docs-related PRs don't require news file. If a contributor just created a blurb file with not meaningful info, it is more difficult to remove the file (from within GitHub UI), but removing a label is easy.

**Comment by jdemeyer** [comment]
This might be easier with bedevere: https://github.com/python/bedevere/issues/175
