### ISSUE TITLE
Release once, release often!

### ISSUE THREAD

**Issue by utkarsh2102** [python/blurb_it#46]
Hey,

I was planning to package this tool for the Debian repositories and for it to happen, the initial requirement is to make a release so that I can get the tar and convert it into a package.  

Thus, requesting you to please make a release of the same.

**Comment by Mariatta** [comment]
Can you clarify what do you mean by packaging this for Debian repositories?  
blurb-it is a web application that you can deploy to Heroku. There is a button in readme for deploying your own instance to Heroku.
blurb-it was written specifically for CPython project (many things are hardcoded), so perhaps you'll need to fork and customize it.

Are you thinking of the `blurb` command line tool? blurb itself is already in PyPI https://pypi.org/project/blurb/

**Comment by Mariatta** [comment]
> There is a button in readme for deploying your own instance to Heroku.

I realized it wasn't actually working. I've created #47 to address that.

**Comment by utkarsh2102** [comment]
> Are you thinking of the blurb command line tool?

Ah, yes. I know blurb is packaged and is there in PyPI but I wanted it to be there in `apt` repositories, too. So that `apt install blurb` works, too :)

**Comment by Mariatta** [comment]
Ah ok, I don't know how packaging to `apt` works. The issue tracker for blurb is still at core-workflow https://github.com/python/core-workflow if you want to raise it there. Thanks.

**Comment by utkarsh2102** [comment]
I am a Debian Maintainer. I can take this forward myself.  So no need to raise an issue here \o/
